# Generated by Django 5.0.6 on 2024-05-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0005_alter_answer_date_alter_job_date_alter_question_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('autumnClimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autumnClimate', to='TravelAgent.climate')),
                ('springClimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='springClimate', to='TravelAgent.climate')),
                ('summerClimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summerClimate', to='TravelAgent.climate')),
                ('winterClimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winterClimate', to='TravelAgent.climate')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stars', models.PositiveSmallIntegerField()),
                ('oneDayPrice', models.PositiveSmallIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='TravelAgent.country')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('duration', models.IntegerField(choices=[(1, 'One week'), (2, 'Two weeks'), (4, 'Four weeks')])),
                ('price', models.PositiveIntegerField(default=1)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='TravelAgent.country')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='TravelAgent.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField(default=1)),
                ('price', models.FloatField()),
                ('startDate', models.DateField()),
                ('createdAt', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='TravelAgent.user')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='TravelAgent.tour')),
            ],
        ),
    ]
