# Generated by Django 5.0.6 on 2024-05-23 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0008_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='\\+\\d{3} \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
