# Generated by Django 5.0.6 on 2024-05-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0010_user_created_at_alter_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
