# Generated by Django 5.0.6 on 2024-05-24 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0011_article_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator(message='+375 (29) XXX-XX-XX;   ', regex='\\+\\d{3} \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('img_url', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
