# Generated by Django 5.1.1 on 2024-09-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0014_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_info', models.CharField(max_length=500)),
                ('video_url', models.CharField(max_length=500)),
                ('logo_url', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=50)),
                ('certificate', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('info', models.CharField(max_length=500)),
            ],
        ),
    ]
