# Generated by Django 5.1.1 on 2024-10-10 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0015_aboutcompany_companyhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcompany',
            name='certificate',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 10, 10)),
        ),
    ]
