# Generated by Django 5.1.1 on 2024-11-23 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelAgent', '0016_alter_aboutcompany_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='last', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default='surn', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 11, 23)),
        ),
    ]
